// Package optionschain implements FEATURES.md §3's "Real-time Options
// Chain: OI, Volume, IV, strike ladder, PCR" and "Greeks computed live per
// contract".
//
// There is no real listed-options market data feed anywhere in this
// repo, so this package builds a SYNTHETIC options chain: given an
// underlying spot price and an expiry date, it generates a strike ladder
// around the money and, for every strike, computes REAL Greeks and a
// real theoretical price by actually calling quant-engine's genuine
// Black-Scholes HTTP API (`POST /options/price`, see
// internal/quantengineclient) — the math for price/delta/gamma/vega/theta
// is 100% real, live-computed by quant-engine, not faked or hardcoded
// here.
//
// LOUD, HONEST GAPS — read before trusting any number this package
// returns as real market data:
//  1. Open Interest and Volume per contract are ILLUSTRATIVE, SYNTHETIC
//     numbers generated by a deterministic formula
//     (calculateSyntheticOpenInterestAndVolume) that shapes a plausible
//     "OI peaks near the money and decays with distance" curve — they are
//     NOT observed from any real exchange or order book. Every number
//     with "Synthetic" in its field name must never be treated as real
//     market depth/interest.
//  2. "Implied Volatility" here is really the ASSUMED volatility this
//     package feeds into the pricer (illustrativeAnnualizedVolatility,
//     flat across every strike/expiry) — NOT a genuine implied volatility
//     SOLVED from an observed market price the way quant-engine's own
//     `POST /options/implied-volatility` endpoint can do. A real options
//     chain shows IV solved per-contract from live bid/ask/last-traded
//     prices, which don't exist here. Reported as
//     AssumedAnnualizedVolatility, not "impliedVolatility", specifically
//     so this honest distinction survives into the JSON contract too.
//  3. The risk-free rate is also a flat illustrative constant
//     (illustrativeAnnualizedRiskFreeInterestRate), not a real
//     government-bond-derived curve.
//
// What IS real: the Put-Call Ratio (PCR = total put OI / total call OI)
// math, the Greeks/theoretical-price values themselves (genuinely
// computed by quant-engine given whatever inputs this package supplies),
// and the strike ladder generation logic.
package optionschain

import (
	"errors"
	"fmt"
	"math"
	"time"

	"mercurius/omsgateway/internal/quantengineclient"
)

// illustrativeAnnualizedRiskFreeInterestRate and
// illustrativeAnnualizedVolatility are flat, made-up inputs fed to
// quant-engine's real pricer for every contract in the chain — see gap
// §2/§3 in the package doc above.
const (
	illustrativeAnnualizedRiskFreeInterestRate = 0.05
	illustrativeAnnualizedVolatility           = 0.20
)

// numberOfStrikesBelowAtm and numberOfStrikesAboveAtm together produce a
// 10-strike ladder (FEATURES.md's "e.g. 10 strikes around ATM") — 5
// strictly below the at-the-money strike and 5 at-or-above it.
const (
	numberOfStrikesBelowAtm = 5
	numberOfStrikesAboveAtm = 5
)

var (
	// ErrUnderlyingSpotPriceMustBePositive is returned when the supplied
	// spot price is zero or negative.
	ErrUnderlyingSpotPriceMustBePositive = errors.New("underlyingSpotPrice must be greater than zero")

	// ErrExpiryMustBeInTheFuture is returned when the supplied expiry
	// date is not strictly after `now` — an already-expired or
	// same-instant contract has no meaningful time value to price.
	ErrExpiryMustBeInTheFuture = errors.New("expiryDate must be in the future relative to now")

	// ErrCannotComputePutCallRatioWithZeroCallOpenInterest is returned by
	// CalculatePutCallRatio when total call open interest is zero — the
	// ratio is mathematically undefined (division by zero), not "0" or
	// "infinite" in any meaningful trading sense.
	ErrCannotComputePutCallRatioWithZeroCallOpenInterest = errors.New("cannot compute put-call ratio: total call open interest is zero")
)

// OptionPricer is the subset of quantengineclient.QuantEngineClient this
// package depends on — an interface so tests can inject a fake pricer
// instead of a real HTTP round-trip.
type OptionPricer interface {
	PriceOptionContract(request quantengineclient.OptionPricingRequest) (quantengineclient.OptionPricingResponse, error)
}

// OptionContractQuote is one side (call or put) of one strike's row in
// the chain.
type OptionContractQuote struct {
	OptionType                        string  `json:"optionType"` // "CALL" or "PUT"
	TheoreticalPriceInMinorUnits      float64 `json:"theoreticalPriceInMinorUnits"`
	Delta                             float64 `json:"delta"`
	Gamma                             float64 `json:"gamma"`
	VegaPerOnePercentVolatilityChange float64 `json:"vegaPerOnePercentVolatilityChange"`
	ThetaPerCalendarDay               float64 `json:"thetaPerCalendarDay"`
	AssumedAnnualizedVolatility       float64 `json:"assumedAnnualizedVolatility"`
	SyntheticOpenInterest             uint64  `json:"syntheticOpenInterest"`
	SyntheticVolume                   uint64  `json:"syntheticVolume"`
}

// StrikeRow is one strike price's call and put quotes side by side —
// the shape a real options-chain UI renders one row from.
type StrikeRow struct {
	StrikePrice float64             `json:"strikePrice"`
	Call        OptionContractQuote `json:"call"`
	Put         OptionContractQuote `json:"put"`
}

// OptionsChainResponse is the full synthetic chain for one underlying/
// expiry pair.
type OptionsChainResponse struct {
	UnderlyingSymbol      string      `json:"underlyingSymbol"`
	UnderlyingSpotPrice   float64     `json:"underlyingSpotPrice"`
	ExpiryDate            string      `json:"expiryDate"`
	TimeToExpiryInYears   float64     `json:"timeToExpiryInYears"`
	Strikes               []StrikeRow `json:"strikes"`
	TotalCallOpenInterest uint64      `json:"totalCallOpenInterest"`
	TotalPutOpenInterest  uint64      `json:"totalPutOpenInterest"`
	PutCallRatio          float64     `json:"putCallRatio"`
}

// CalculatePutCallRatio computes PCR = total put OI / total call OI — the
// one piece of real, tested math in this package that doesn't depend on
// the OI inputs themselves being real (see package doc). Returns
// ErrCannotComputePutCallRatioWithZeroCallOpenInterest rather than
// silently returning +Inf or 0 for a zero-call-OI chain.
func CalculatePutCallRatio(totalPutOpenInterest uint64, totalCallOpenInterest uint64) (float64, error) {
	if totalCallOpenInterest == 0 {
		return 0, ErrCannotComputePutCallRatioWithZeroCallOpenInterest
	}
	return float64(totalPutOpenInterest) / float64(totalCallOpenInterest), nil
}

// calculateStrikeIntervalForSpotPrice picks a "reasonable" strike
// spacing for a given spot price magnitude — a small, illustrative,
// order-of-magnitude table in the same spirit as chargescalculator's/
// marginpledge's illustrative rate tables (documented, not a real
// exchange strike-listing convention).
func calculateStrikeIntervalForSpotPrice(underlyingSpotPrice float64) float64 {
	switch {
	case underlyingSpotPrice < 100:
		return 1
	case underlyingSpotPrice < 1000:
		return 10
	case underlyingSpotPrice < 10000:
		return 50
	default:
		return 100
	}
}

// generateStrikeLadder returns numberOfStrikesBelowAtm+numberOfStrikesAboveAtm
// strike prices, evenly spaced by calculateStrikeIntervalForSpotPrice's
// interval, centered on the spot price rounded to the nearest interval
// (the "at-the-money" strike).
func generateStrikeLadder(underlyingSpotPrice float64) []float64 {
	interval := calculateStrikeIntervalForSpotPrice(underlyingSpotPrice)
	atmStrike := math.Round(underlyingSpotPrice/interval) * interval

	strikes := make([]float64, 0, numberOfStrikesBelowAtm+numberOfStrikesAboveAtm)
	for i := -numberOfStrikesBelowAtm; i < numberOfStrikesAboveAtm; i++ {
		strikes = append(strikes, atmStrike+float64(i)*interval)
	}
	return strikes
}

// calculateSyntheticOpenInterestAndVolume produces a plausible-but-fake
// OI/Volume pair for one contract: OI peaks at the at-the-money strike
// (distanceFromAtmInStrikes == 0) and decays smoothly with distance,
// exactly the shape real options OI curves tend to follow — but every
// number here is a deterministic formula, not observed data. Puts get a
// modest illustrative skew multiplier (puts often carry more OI due to
// hedging demand) purely to make the PCR come out somewhere other than
// exactly 1.0 in the common case — again, an assumption, not a fact.
func calculateSyntheticOpenInterestAndVolume(distanceFromAtmInStrikes int, isCallOptionNotPut bool) (openInterest uint64, volume uint64) {
	const baseOpenInterest = 50_000
	const putSkewMultiplier = 1.15

	if distanceFromAtmInStrikes < 0 {
		distanceFromAtmInStrikes = -distanceFromAtmInStrikes
	}
	decayFactor := 1.0 / (1.0 + float64(distanceFromAtmInStrikes)*0.4)

	oiFloat := float64(baseOpenInterest) * decayFactor
	if !isCallOptionNotPut {
		oiFloat *= putSkewMultiplier
	}
	openInterest = uint64(math.Round(oiFloat))
	// Volume is illustratively modeled as roughly an eighth of OI,
	// decaying slightly faster with distance from the money (far
	// strikes trade less often relative to their resting OI, a real,
	// commonly observed pattern this formula only loosely mimics).
	volumeFloat := oiFloat / 8.0 * (1.0 / (1.0 + float64(distanceFromAtmInStrikes)*0.15))
	volume = uint64(math.Round(volumeFloat))
	return openInterest, volume
}

// GenerateSyntheticOptionsChain builds the full chain described in the
// package doc: a real strike ladder, synthetic OI/Volume, and REAL
// Greeks/theoretical price for every contract via `pricer` (quant-engine
// over HTTP in production, a fake in tests). `now` is passed explicitly
// (not read from the wall clock inside this function) so time-to-expiry
// is deterministic and testable — the HTTP handler in cmd/server/main.go
// supplies time.Now().
//
// Returns an error immediately, without partially building a chain, if:
//   - underlyingSpotPrice isn't positive
//   - expiryDate isn't strictly after now
//   - quant-engine is unreachable or rejects any single contract's
//     pricing request (see the package doc's "handle quant-engine being
//     unreachable gracefully" requirement — this returns a clear,
//     wrapped error rather than letting oms-gateway crash or hang)
func GenerateSyntheticOptionsChain(
	pricer OptionPricer,
	underlyingSymbol string,
	underlyingSpotPrice float64,
	expiryDate time.Time,
	now time.Time,
) (OptionsChainResponse, error) {
	if underlyingSpotPrice <= 0 {
		return OptionsChainResponse{}, ErrUnderlyingSpotPriceMustBePositive
	}
	if !expiryDate.After(now) {
		return OptionsChainResponse{}, ErrExpiryMustBeInTheFuture
	}

	timeToExpiryInYears := expiryDate.Sub(now).Hours() / 24 / 365

	strikeLadder := generateStrikeLadder(underlyingSpotPrice)
	atmIndex := numberOfStrikesBelowAtm // strikeLadder[atmIndex] is the first at-or-above-ATM strike

	strikeRows := make([]StrikeRow, 0, len(strikeLadder))
	var totalCallOpenInterest, totalPutOpenInterest uint64

	for index, strikePrice := range strikeLadder {
		distanceFromAtm := index - atmIndex

		callQuote, callError := priceOneContract(pricer, underlyingSpotPrice, strikePrice, timeToExpiryInYears, true, distanceFromAtm)
		if callError != nil {
			return OptionsChainResponse{}, fmt.Errorf("failed to price call contract at strike %.2f: %w", strikePrice, callError)
		}
		putQuote, putError := priceOneContract(pricer, underlyingSpotPrice, strikePrice, timeToExpiryInYears, false, distanceFromAtm)
		if putError != nil {
			return OptionsChainResponse{}, fmt.Errorf("failed to price put contract at strike %.2f: %w", strikePrice, putError)
		}

		totalCallOpenInterest += callQuote.SyntheticOpenInterest
		totalPutOpenInterest += putQuote.SyntheticOpenInterest

		strikeRows = append(strikeRows, StrikeRow{
			StrikePrice: strikePrice,
			Call:        callQuote,
			Put:         putQuote,
		})
	}

	putCallRatio, pcrError := CalculatePutCallRatio(totalPutOpenInterest, totalCallOpenInterest)
	if pcrError != nil {
		// Every real-world chain with any call OI at all avoids this —
		// only reachable if every single synthetic call OI rounded to
		// zero, which calculateSyntheticOpenInterestAndVolume's formula
		// never produces for the illustrative constants above. Kept as a
		// real, non-panicking fallback rather than assuming it can't
		// happen.
		putCallRatio = 0
	}

	return OptionsChainResponse{
		UnderlyingSymbol:      underlyingSymbol,
		UnderlyingSpotPrice:   underlyingSpotPrice,
		ExpiryDate:            expiryDate.Format("2006-01-02"),
		TimeToExpiryInYears:   timeToExpiryInYears,
		Strikes:               strikeRows,
		TotalCallOpenInterest: totalCallOpenInterest,
		TotalPutOpenInterest:  totalPutOpenInterest,
		PutCallRatio:          putCallRatio,
	}, nil
}

func priceOneContract(
	pricer OptionPricer,
	underlyingSpotPrice float64,
	strikePrice float64,
	timeToExpiryInYears float64,
	isCallOptionNotPut bool,
	distanceFromAtm int,
) (OptionContractQuote, error) {
	pricingResponse, pricingError := pricer.PriceOptionContract(quantengineclient.OptionPricingRequest{
		UnderlyingSpotPrice:            underlyingSpotPrice,
		OptionStrikePrice:              strikePrice,
		AnnualizedRiskFreeInterestRate: illustrativeAnnualizedRiskFreeInterestRate,
		AnnualizedVolatility:           illustrativeAnnualizedVolatility,
		TimeToExpiryInYears:            timeToExpiryInYears,
		IsCallOptionNotPut:             isCallOptionNotPut,
	})
	if pricingError != nil {
		return OptionContractQuote{}, pricingError
	}

	openInterest, volume := calculateSyntheticOpenInterestAndVolume(distanceFromAtm, isCallOptionNotPut)

	optionType := "PUT"
	if isCallOptionNotPut {
		optionType = "CALL"
	}

	return OptionContractQuote{
		OptionType:                        optionType,
		TheoreticalPriceInMinorUnits:      pricingResponse.TheoreticalPriceInMinorUnits,
		Delta:                             pricingResponse.Delta,
		Gamma:                             pricingResponse.Gamma,
		VegaPerOnePercentVolatilityChange: pricingResponse.VegaPerOnePercentVolatilityChange,
		ThetaPerCalendarDay:               pricingResponse.ThetaPerCalendarDay,
		AssumedAnnualizedVolatility:       illustrativeAnnualizedVolatility,
		SyntheticOpenInterest:             openInterest,
		SyntheticVolume:                   volume,
	}, nil
}
