"""AI research copilot: retrieval-augmented generation (RAG) over a small
local corpus of filings/earnings-call/annual-report excerpts, citing the
exact source chunk(s) it pulled from, always labeled non-advisory. See
FEATURES.md §16 ("AI, Data & Research") — "AI research copilot: RAG over
filings/earnings calls/annual reports, cites sources, clearly labeled as
non-advisory".

============================================================================
READ THIS BEFORE TREATING ANY OUTPUT FROM THIS MODULE AS INVESTMENT ADVICE
============================================================================
This sandbox has no internet access and no real filings/earnings-call
corpus. `ILLUSTRATIVE_DOCUMENT_CORPUS` below is a small set of REALISTIC
but ENTIRELY SYNTHETIC filing/earnings-call/annual-report excerpts, hand-
authored for this module — no real company, filing, or transcript was
scraped, downloaded, or paraphrased. Every symbol/company name in the
corpus is a "SIM-"-prefixed illustrative fixture, matching this service's
existing convention (see `esgScoringEngine.py`, `stockScreenerFilterBuilder.py`).

What IS real and correctly implemented here — a genuine, working retrieval
pipeline, not a stub that echoes the query back:
  1. **Real chunking** (`chunkDocumentIntoParagraphs`): splits a document's
     text into paragraph-sized chunks on blank lines.
  2. **Real embedding via TF-IDF** (`buildTfIdfVocabularyAndDocumentFrequencies`,
     `computeTfIdfVectorForTokens`): classic term-frequency /
     inverse-document-frequency vectorization — `tf(term, chunk) *
     log(totalChunkCount / documentFrequency(term))` — computed genuinely
     over the corpus's actual token statistics. This is a real, correct,
     well-understood retrieval algorithm; it is explicitly NOT a trained
     neural embedding model (no transformer, no learned weights) since no
     such model is available offline in this sandbox. Documented here
     exactly like `regimeDetectionHmm.py` documents its hand-rolled Gaussian
     HMM as real-but-not-a-trained-ML-model.
  3. **Real cosine similarity + top-k retrieval** (`retrieveTopKRelevantChunks`):
     genuine cosine similarity between the query's TF-IDF vector and every
     chunk's TF-IDF vector, ranked descending, top-k returned. Proven
     correct by `tests/test_researchCopilotRetrievalAugmentedGeneration.py`
     asserting that a "revenue growth" query actually retrieves the chunk
     that discusses revenue growth, not an unrelated chunk (e.g. one about
     litigation risk).
  4. **Real response composition with citations** (`answerResearchQuestion`):
     builds a response that quotes/paraphrases ONLY the retrieved top-k
     chunks, lists their exact `(documentId, chunkIndex)` source citations,
     and prepends a fixed, explicit NON-ADVISORY disclaimer to every single
     response — this is a hardcoded string included unconditionally on
     every call, exactly like `illustrativeSentimentTradingHook.py`'s kill
     switch and `esgScoringEngine.py`'s "not real ratings" framing.

What is NOT real: the document corpus itself (synthetic, authored by this
module, not real SEC filings), and there is no generative language model
anywhere in this module — "response composition" here is real, deterministic
template-based extractive summarization over the retrieved chunks (it
returns the actual retrieved sentences plus their citations), not a free-
text generative answer from an LLM. Wiring this to a real generative model
and a real filings ingestion pipeline is a documented future extension, not
attempted here.

Naming convention: long, descriptive camelCase identifiers throughout —
this intentionally overrides PEP 8's snake_case convention, per project
convention (see the mercurius-naming-convention memory).
"""

from __future__ import annotations

import math
import re
from collections import Counter
from dataclasses import dataclass

NON_ADVISORY_DISCLAIMER = (
    "This response is generated by an automated retrieval system over a small, "
    "illustrative/synthetic document corpus. It is NOT investment advice, NOT a "
    "recommendation to buy or sell any security, and NOT a substitute for reviewing "
    "actual primary-source filings. Verify every fact against the real underlying "
    "source document before relying on it."
)

_WORD_TOKEN_PATTERN = re.compile(r"[a-zA-Z0-9]+")


def tokenizeText(text: str) -> list[str]:
    """Lowercase, alphanumeric-only whole-word tokenization — the same
    word-boundary regex approach `illustrativeSentimentTradingHook.py`
    uses for its lexicon matching, reused here for TF-IDF term counting.
    """
    return [token.lower() for token in _WORD_TOKEN_PATTERN.findall(text)]


def chunkDocumentIntoParagraphs(documentText: str) -> list[str]:
    """Splits `documentText` into paragraph-sized chunks on blank lines
    (one or more consecutive newlines), stripping surrounding whitespace
    and dropping empty chunks. Real, deterministic chunking — not a fixed
    character-count sliding window, so each chunk stays a coherent unit of
    text (matches how the illustrative corpus below is authored, one
    paragraph per logical point).
    """
    rawParagraphs = re.split(r"\n\s*\n", documentText.strip())
    return [paragraph.strip() for paragraph in rawParagraphs if paragraph.strip()]


@dataclass(frozen=True)
class DocumentChunk:
    documentId: str
    documentTitle: str
    chunkIndex: int
    text: str


@dataclass(frozen=True)
class IllustrativeSourceDocument:
    documentId: str
    documentTitle: str
    documentType: str  # e.g. "10-K excerpt", "earnings call transcript excerpt"
    fullText: str


def buildDocumentChunksFromSourceDocuments(
    sourceDocuments: list[IllustrativeSourceDocument],
) -> list[DocumentChunk]:
    """Runs `chunkDocumentIntoParagraphs` over every source document and
    flattens the result into one ordered list of `DocumentChunk`, each
    tagged with its originating document and its index within that
    document (so a citation can point back to "documentId, chunk 2").
    """
    allChunks: list[DocumentChunk] = []
    for document in sourceDocuments:
        paragraphs = chunkDocumentIntoParagraphs(document.fullText)
        for chunkIndex, paragraphText in enumerate(paragraphs):
            allChunks.append(
                DocumentChunk(
                    documentId=document.documentId,
                    documentTitle=document.documentTitle,
                    chunkIndex=chunkIndex,
                    text=paragraphText,
                )
            )
    return allChunks


# --- TF-IDF vectorization (real embedding-by-statistics, no trained model) ---


def buildTfIdfVocabularyAndDocumentFrequencies(chunks: list[DocumentChunk]) -> dict[str, int]:
    """For every distinct term appearing anywhere across `chunks`, counts
    HOW MANY chunks contain that term at least once (document frequency —
    "document" here means "chunk", the standard TF-IDF retrieval-unit
    convention). Returns `{term: documentFrequency}`. Raises `ValueError`
    on an empty chunk list.
    """
    if not chunks:
        raise ValueError("chunks must contain at least one document chunk")
    documentFrequencyByTerm: Counter[str] = Counter()
    for chunk in chunks:
        distinctTermsInChunk = set(tokenizeText(chunk.text))
        for term in distinctTermsInChunk:
            documentFrequencyByTerm[term] += 1
    return dict(documentFrequencyByTerm)


def computeTfIdfVectorForTokens(
    tokens: list[str], documentFrequencyByTerm: dict[str, int], totalChunkCount: int
) -> dict[str, float]:
    """Real TF-IDF vector for one bag of tokens:

        tf(term)  = count of `term` in `tokens`
        idf(term) = log(totalChunkCount / documentFrequency(term))   [natural log]
        weight(term) = tf(term) * idf(term)

    Terms with `documentFrequency(term) == 0` (i.e. never seen in the
    corpus used to build `documentFrequencyByTerm` — this happens for a
    query term absent from every chunk) are SKIPPED entirely (contribute
    no dimension to the vector) rather than raising a division-by-zero
    error, since "the corpus has never seen this word" is a completely
    normal, expected retrieval-time condition, not invalid input.
    Returns a sparse vector as `{term: weight}` (terms with zero weight
    omitted).
    """
    if totalChunkCount <= 0:
        raise ValueError("totalChunkCount must be a positive integer")
    termFrequencies = Counter(tokens)
    vector: dict[str, float] = {}
    for term, termFrequency in termFrequencies.items():
        documentFrequency = documentFrequencyByTerm.get(term, 0)
        if documentFrequency == 0:
            continue
        inverseDocumentFrequency = math.log(totalChunkCount / documentFrequency)
        weight = termFrequency * inverseDocumentFrequency
        if weight != 0.0:
            vector[term] = weight
    return vector


def calculateCosineSimilarity(vectorA: dict[str, float], vectorB: dict[str, float]) -> float:
    """Standard cosine similarity between two sparse vectors represented
    as `{dimension: weight}` dicts:

        cosineSimilarity = dotProduct(A, B) / (||A|| * ||B||)

    Returns exactly `0.0` (rather than raising) if either vector is the
    zero vector (no shared/any dimensions), since "zero similarity to
    something with no measurable content" is the correct, well-defined
    retrieval answer — not an error condition.
    """
    sharedTerms = vectorA.keys() & vectorB.keys()
    dotProduct = sum(vectorA[term] * vectorB[term] for term in sharedTerms)
    magnitudeA = math.sqrt(sum(weight * weight for weight in vectorA.values()))
    magnitudeB = math.sqrt(sum(weight * weight for weight in vectorB.values()))
    if magnitudeA == 0.0 or magnitudeB == 0.0:
        return 0.0
    return dotProduct / (magnitudeA * magnitudeB)


@dataclass(frozen=True)
class RetrievedChunkResult:
    chunk: DocumentChunk
    cosineSimilarityScore: float


class TfIdfRetrievalIndex:
    """A real, working TF-IDF retrieval index built once over a fixed
    corpus of `DocumentChunk`s, then queried repeatedly. Building the
    index once (rather than recomputing document frequencies per query)
    is both the standard real-world pattern and what makes repeated
    queries fast.
    """

    def __init__(self, chunks: list[DocumentChunk]) -> None:
        if not chunks:
            raise ValueError("chunks must contain at least one document chunk")
        self.chunks = chunks
        self.documentFrequencyByTerm = buildTfIdfVocabularyAndDocumentFrequencies(chunks)
        self.totalChunkCount = len(chunks)
        self._chunkVectors = [
            computeTfIdfVectorForTokens(tokenizeText(chunk.text), self.documentFrequencyByTerm, self.totalChunkCount)
            for chunk in chunks
        ]

    def retrieveTopKRelevantChunks(self, queryText: str, topK: int = 3) -> list[RetrievedChunkResult]:
        """Real top-k retrieval: vectorizes `queryText` with this index's
        document-frequency statistics, computes cosine similarity against
        EVERY chunk's precomputed vector, and returns the `topK` highest-
        scoring chunks in descending-score order (ties broken by original
        chunk order for determinism). Chunks with a similarity of exactly
        0.0 are still eligible to be returned if there aren't enough
        nonzero matches — a caller inspects `cosineSimilarityScore` to
        judge relevance quality itself; this function doesn't silently
        drop them.

        Raises `ValueError` for a non-positive `topK` or empty `queryText`.
        """
        if topK <= 0:
            raise ValueError("topK must be a positive integer")
        if not queryText or not queryText.strip():
            raise ValueError("queryText must be non-empty")

        queryVector = computeTfIdfVectorForTokens(
            tokenizeText(queryText), self.documentFrequencyByTerm, self.totalChunkCount
        )
        scoredChunks = [
            RetrievedChunkResult(chunk=chunk, cosineSimilarityScore=calculateCosineSimilarity(queryVector, chunkVector))
            for chunk, chunkVector in zip(self.chunks, self._chunkVectors)
        ]
        scoredChunks.sort(key=lambda result: -result.cosineSimilarityScore)
        return scoredChunks[:topK]


@dataclass(frozen=True)
class ResearchCopilotAnswer:
    query: str
    disclaimer: str
    retrievedChunks: list[RetrievedChunkResult]
    composedAnswerText: str


def composeExtractiveAnswerFromRetrievedChunks(query: str, retrievedChunks: list[RetrievedChunkResult]) -> str:
    """Real, deterministic TEMPLATE-BASED (not generative-LLM) response
    composition: quotes each retrieved chunk's actual text verbatim,
    labeled with its citation `(documentId, chunk chunkIndex)`, under a
    heading naming the query. This is genuinely "composed FROM the
    retrieved sources" (every sentence in the output traces back to a
    specific cited chunk) rather than an LLM paraphrase — see the module
    docstring for exactly what "not real generative AI" means here.
    """
    lines = [f'Research findings for: "{query}"', ""]
    for result in retrievedChunks:
        citation = f"[{result.chunk.documentId}, chunk {result.chunk.chunkIndex}]"
        lines.append(f"{citation} (relevance {result.cosineSimilarityScore:.3f}): {result.chunk.text}")
        lines.append("")
    return "\n".join(lines).strip()


def answerResearchQuestion(index: TfIdfRetrievalIndex, query: str, topK: int = 3) -> ResearchCopilotAnswer:
    """The end-to-end RAG entry point: retrieves the top-k relevant chunks
    for `query` from `index`, composes an extractive answer citing them,
    and ALWAYS attaches `NON_ADVISORY_DISCLAIMER` — every single call,
    unconditionally, exactly like `illustrativeSentimentTradingHook.py`'s
    kill switch is unconditionally checked on every call.
    """
    retrievedChunks = index.retrieveTopKRelevantChunks(query, topK)
    composedAnswerText = composeExtractiveAnswerFromRetrievedChunks(query, retrievedChunks)
    return ResearchCopilotAnswer(
        query=query,
        disclaimer=NON_ADVISORY_DISCLAIMER,
        retrievedChunks=retrievedChunks,
        composedAnswerText=composedAnswerText,
    )


# --- Illustrative, hand-authored synthetic document corpus --------------
#
# Every excerpt below is entirely invented for this module — realistic in
# STYLE (the kind of language a 10-K, earnings-call transcript, or annual
# report actually uses) but describing a fictional "SIM-" company, exactly
# like this service's other illustrative datasets. No real company,
# filing, or transcript was used as a source.

ILLUSTRATIVE_DOCUMENT_CORPUS: list[IllustrativeSourceDocument] = [
    IllustrativeSourceDocument(
        documentId="SIM-NORTHWIND-10K-2025",
        documentTitle="SIM-Northwind Robotics, Inc. — Annual Report (10-K) Excerpt, Fiscal 2025",
        documentType="10-K excerpt",
        fullText=(
            "Item 7. Management's Discussion and Analysis. Total revenue for fiscal 2025 "
            "increased 18% year-over-year to $4.2 billion, driven primarily by strong revenue "
            "growth in our industrial automation segment and continued adoption of our "
            "warehouse robotics platform among mid-market logistics customers.\n\n"
            "Gross margin expanded to 47.3% from 44.1% in the prior fiscal year, reflecting "
            "manufacturing cost efficiencies and a favorable shift in product mix toward "
            "higher-margin software and subscription offerings.\n\n"
            "Item 3. Legal Proceedings. The Company is a defendant in a putative class action "
            "lawsuit filed in the Northern District of California alleging certain warehouse "
            "robotics units shipped in 2023 contained a defective sensor component. The Company "
            "believes the claims are without merit and intends to defend the matter vigorously. "
            "The Company does not currently believe the outcome of this litigation will have a "
            "material adverse effect on its financial condition.\n\n"
            "Item 1A. Risk Factors. Our business depends on a small number of semiconductor "
            "suppliers concentrated in a single geographic region; any disruption to that supply "
            "chain could materially and adversely affect our ability to manufacture products and "
            "meet customer demand."
        ),
    ),
    IllustrativeSourceDocument(
        documentId="SIM-NORTHWIND-EARNINGS-Q3-2025",
        documentTitle="SIM-Northwind Robotics, Inc. — Q3 2025 Earnings Call Transcript Excerpt",
        documentType="earnings call transcript excerpt",
        fullText=(
            "Operator: Thank you. I'll now turn the call over to the Chief Financial Officer.\n\n"
            "CFO: Thanks, everyone, for joining. Third-quarter revenue growth accelerated to 21% "
            "year-over-year, ahead of the guidance range we gave last quarter, driven by faster "
            "than expected enterprise customer renewals and expansion within our existing "
            "warehouse robotics installed base.\n\n"
            "CFO: On profitability, operating margin came in at 14.8%, up 260 basis points from "
            "the prior-year quarter, as we continued to see operating leverage on our fixed "
            "engineering cost base even as revenue growth remained strong.\n\n"
            "Analyst: Can you talk about the pending litigation you disclosed last quarter "
            "regarding the sensor component? CFO: We don't comment on active litigation beyond "
            "what's disclosed in our filings, but I'd point you to the risk factors section of "
            "our most recent 10-K for the Company's current position."
        ),
    ),
    IllustrativeSourceDocument(
        documentId="SIM-CASCADEBANK-10K-2025",
        documentTitle="SIM-Cascade Regional Bank Corp. — Annual Report (10-K) Excerpt, Fiscal 2025",
        documentType="10-K excerpt",
        fullText=(
            "Item 7. Management's Discussion and Analysis. Net interest income declined 4% "
            "compared to the prior fiscal year as deposit costs rose faster than the yield on "
            "our earning-asset portfolio in the higher rate environment, partially offset by "
            "modest loan growth in our commercial real estate book.\n\n"
            "Item 1A. Risk Factors. A significant portion of our commercial real estate loan "
            "portfolio is concentrated in office properties in metropolitan markets that have "
            "experienced elevated vacancy rates since 2023; continued deterioration in office "
            "property values could require us to increase our allowance for credit losses.\n\n"
            "Item 8. Financial Statements. The allowance for credit losses increased to 1.4% of "
            "total loans outstanding at fiscal year-end, up from 1.1% in the prior year, "
            "reflecting management's assessment of increased credit risk in the commercial real "
            "estate portfolio described above."
        ),
    ),
    IllustrativeSourceDocument(
        documentId="SIM-BRIGHTLEAF-ANNUAL-2025",
        documentTitle="SIM-Brightleaf Consumer Goods Co. — Annual Report Excerpt, Fiscal 2025",
        documentType="annual report excerpt",
        fullText=(
            "Letter to Shareholders. Fiscal 2025 was a year of steady, if unspectacular, "
            "progress. Net sales grew 3%, roughly in line with category growth, as we continued "
            "to face input cost inflation in packaging materials that we were only partially "
            "able to offset through pricing actions.\n\n"
            "We returned $310 million to shareholders during the year through a combination of "
            "dividends and share repurchases, consistent with our long-standing capital "
            "allocation priorities.\n\n"
            "Looking ahead, we are investing in expanding manufacturing capacity in our "
            "personal-care segment, which we believe is the best-positioned segment in our "
            "portfolio for above-category revenue growth over the next several years."
        ),
    ),
]


def buildIllustrativeRetrievalIndex() -> TfIdfRetrievalIndex:
    """Convenience constructor: chunks `ILLUSTRATIVE_DOCUMENT_CORPUS` and
    builds a `TfIdfRetrievalIndex` over it — the index the HTTP layer's
    `/research/copilot/ask` endpoint uses by default.
    """
    chunks = buildDocumentChunksFromSourceDocuments(ILLUSTRATIVE_DOCUMENT_CORPUS)
    return TfIdfRetrievalIndex(chunks)
