import math

import pytest

from quantengine.volatilitySurfaceBuilder import (
    OptionMarketQuote,
    VolatilitySurface,
    VolatilitySurfacePoint,
    buildVolatilitySurfaceFromMarketQuotes,
)

# --- Fixture quotes -------------------------------------------------------
# Market prices below were generated by pricing known volatilities through
# blackScholesOptionPricer.calculateBlackScholesCallOptionPrice (spot=100,
# r=0.05, expiry=0.5 years) -- exactly the same "round trip" pattern
# test_httpServer.py's IV endpoint test uses -- so solving IV back out of
# each price should recover (to solver tolerance) the volatility that
# produced it:
#   strike=90,  iv=0.25 -> price=14.437116236460668
#   strike=100, iv=0.20 -> price=6.888728577680624
#   strike=110, iv=0.22 -> price=3.4273163416851844
EXPIRY = 0.5
FIXTURE_QUOTES = [
    OptionMarketQuote(
        optionStrikePrice=90.0,
        expiryInYears=EXPIRY,
        observedMarketPrice=14.437116236460668,
        underlyingSpotPrice=100.0,
        annualizedRiskFreeInterestRate=0.05,
        isCallOptionNotPut=True,
    ),
    OptionMarketQuote(
        optionStrikePrice=100.0,
        expiryInYears=EXPIRY,
        observedMarketPrice=6.888728577680624,
        underlyingSpotPrice=100.0,
        annualizedRiskFreeInterestRate=0.05,
        isCallOptionNotPut=True,
    ),
    OptionMarketQuote(
        optionStrikePrice=110.0,
        expiryInYears=EXPIRY,
        observedMarketPrice=3.4273163416851844,
        underlyingSpotPrice=100.0,
        annualizedRiskFreeInterestRate=0.05,
        isCallOptionNotPut=True,
    ),
]


def test_buildSurfaceSolvesEachQuoteBackToItsKnownVolatility():
    surface = buildVolatilitySurfaceFromMarketQuotes(FIXTURE_QUOTES)
    assert surface.getGridPointCount() == 3
    assert surface.queryImpliedVolatility(EXPIRY, 90.0) == pytest.approx(0.25, abs=1e-4)
    assert surface.queryImpliedVolatility(EXPIRY, 100.0) == pytest.approx(0.20, abs=1e-4)
    assert surface.queryImpliedVolatility(EXPIRY, 110.0) == pytest.approx(0.22, abs=1e-4)


def test_buildSurfaceRaisesOnEmptyQuoteList():
    with pytest.raises(ValueError):
        buildVolatilitySurfaceFromMarketQuotes([])


# --- Hand-worked interpolation case ---------------------------------------
# At EXPIRY, grid strikes/IVs: 90 -> 0.25, 100 -> 0.20, 110 -> 0.22
# Query strike=95 (between 90 and 100):
#   fraction = (95-90)/(100-90) = 0.5
#   iv = 0.25 + 0.5*(0.20-0.25) = 0.25 - 0.025 = 0.225
# Query strike=105 (between 100 and 110):
#   fraction = (105-100)/(110-100) = 0.5
#   iv = 0.20 + 0.5*(0.22-0.20) = 0.20 + 0.01 = 0.21
# Query strike=92 (between 90 and 100, non-midpoint):
#   fraction = (92-90)/(100-90) = 0.2
#   iv = 0.25 + 0.2*(0.20-0.25) = 0.25 - 0.01 = 0.24


def buildDirectSurfaceForInterpolationTests() -> VolatilitySurface:
    return VolatilitySurface(
        [
            VolatilitySurfacePoint(expiryInYears=EXPIRY, optionStrikePrice=90.0, impliedVolatility=0.25),
            VolatilitySurfacePoint(expiryInYears=EXPIRY, optionStrikePrice=100.0, impliedVolatility=0.20),
            VolatilitySurfacePoint(expiryInYears=EXPIRY, optionStrikePrice=110.0, impliedVolatility=0.22),
        ]
    )


def test_interpolationAtMidpointBetween90And100MatchesHandWorkedValue():
    surface = buildDirectSurfaceForInterpolationTests()
    assert math.isclose(surface.queryImpliedVolatility(EXPIRY, 95.0), 0.225, rel_tol=1e-12)


def test_interpolationAtMidpointBetween100And110MatchesHandWorkedValue():
    surface = buildDirectSurfaceForInterpolationTests()
    assert math.isclose(surface.queryImpliedVolatility(EXPIRY, 105.0), 0.21, rel_tol=1e-12)


def test_interpolationAtNonMidpointMatchesHandWorkedValue():
    surface = buildDirectSurfaceForInterpolationTests()
    assert math.isclose(surface.queryImpliedVolatility(EXPIRY, 92.0), 0.24, rel_tol=1e-9)


def test_queryExactGridStrikeReturnsStoredValueDirectly():
    surface = buildDirectSurfaceForInterpolationTests()
    assert surface.queryImpliedVolatility(EXPIRY, 100.0) == 0.20


def test_queryBelowLowestStrikeClampsToBoundaryValue():
    surface = buildDirectSurfaceForInterpolationTests()
    assert surface.queryImpliedVolatility(EXPIRY, 50.0) == 0.25


def test_queryAboveHighestStrikeClampsToBoundaryValue():
    surface = buildDirectSurfaceForInterpolationTests()
    assert surface.queryImpliedVolatility(EXPIRY, 200.0) == 0.22


def test_queryUnknownExpiryRaisesKeyError():
    surface = buildDirectSurfaceForInterpolationTests()
    with pytest.raises(KeyError):
        surface.queryImpliedVolatility(1.0, 100.0)


def test_surfaceConstructorRaisesOnEmptyPoints():
    with pytest.raises(ValueError):
        VolatilitySurface([])


def test_surfaceSupportsMultipleExpiriesIndependently():
    points = [
        VolatilitySurfacePoint(expiryInYears=0.25, optionStrikePrice=100.0, impliedVolatility=0.30),
        VolatilitySurfacePoint(expiryInYears=0.25, optionStrikePrice=110.0, impliedVolatility=0.28),
        VolatilitySurfacePoint(expiryInYears=1.0, optionStrikePrice=100.0, impliedVolatility=0.18),
        VolatilitySurfacePoint(expiryInYears=1.0, optionStrikePrice=110.0, impliedVolatility=0.19),
    ]
    surface = VolatilitySurface(points)
    assert surface.queryImpliedVolatility(0.25, 100.0) == 0.30
    assert surface.queryImpliedVolatility(1.0, 100.0) == 0.18
    # interpolated midpoint at each expiry is independent of the other
    assert math.isclose(surface.queryImpliedVolatility(0.25, 105.0), 0.29, rel_tol=1e-9)
    assert math.isclose(surface.queryImpliedVolatility(1.0, 105.0), 0.185, rel_tol=1e-9)
