// Package mfastate tracks per-account MFA (TOTP) enrollment and gates
// login on it once enabled — FEATURES.md §1: "MFA (TOTP + SMS
// fallback), device binding, biometric unlock (mobile)". This package
// covers TOTP only: no SMS fallback, no device binding, no biometric
// (mobile-only anyway, and FEATURES.md/[[mercurius-platform-scope]]
// deprioritizes mobile for now).
package mfastate

import (
	"sync"
	"time"

	"mercurius/auth/internal/totp"
)

const verificationSkewSteps = 1

type mfaRecord struct {
	secretBase32 string
	isEnabled    bool
}

// MfaState is safe for concurrent use.
//
// TODO(real build): in-memory only — every enrollment is lost on
// restart, which would lock every enrolled user out of their own
// account (the secret is gone, but the account still "requires" MFA per
// whatever persisted state a real build would have). A real build must
// persist this, and probably also store encrypted backup codes for
// account recovery — not built here.
type MfaState struct {
	mutexGuardingRecords sync.Mutex
	recordsByAccountId   map[string]*mfaRecord
}

func NewMfaState() *MfaState {
	return &MfaState{recordsByAccountId: make(map[string]*mfaRecord)}
}

// BeginEnrollment generates a fresh secret for accountIdentifier and
// stores it as NOT YET enabled — MFA only actually starts being
// required at login once ConfirmEnrollment proves the user can produce
// a valid code from it (proving they actually saved/scanned the secret
// correctly, rather than locking them out immediately on a secret they
// might not have set up right).
func (state *MfaState) BeginEnrollment(accountIdentifier string) (secretBase32 string, err error) {
	newSecret, genError := totp.GenerateRandomSecret()
	if genError != nil {
		return "", genError
	}

	state.mutexGuardingRecords.Lock()
	defer state.mutexGuardingRecords.Unlock()
	state.recordsByAccountId[accountIdentifier] = &mfaRecord{secretBase32: newSecret, isEnabled: false}

	return newSecret, nil
}

// ConfirmEnrollment activates MFA for accountIdentifier if candidateCode
// is a valid TOTP code for the secret generated by BeginEnrollment.
// Returns false (not an error) for "no enrollment in progress" and
// "wrong code" alike — both just mean "not confirmed."
func (state *MfaState) ConfirmEnrollment(accountIdentifier string, candidateCode string, now time.Time) (bool, error) {
	state.mutexGuardingRecords.Lock()
	record, wasFound := state.recordsByAccountId[accountIdentifier]
	state.mutexGuardingRecords.Unlock()

	if !wasFound {
		return false, nil
	}

	isValid, verifyError := totp.VerifyCode(record.secretBase32, candidateCode, now, verificationSkewSteps)
	if verifyError != nil {
		return false, verifyError
	}
	if !isValid {
		return false, nil
	}

	state.mutexGuardingRecords.Lock()
	record.isEnabled = true
	state.mutexGuardingRecords.Unlock()

	return true, nil
}

// IsMfaEnabled reports whether accountIdentifier has a CONFIRMED (not
// just begun) MFA enrollment — this is what login should gate on.
func (state *MfaState) IsMfaEnabled(accountIdentifier string) bool {
	state.mutexGuardingRecords.Lock()
	defer state.mutexGuardingRecords.Unlock()

	record, wasFound := state.recordsByAccountId[accountIdentifier]
	return wasFound && record.isEnabled
}

// VerifyLoginCode checks a TOTP code presented at login time against an
// already-enabled enrollment. Returns false for an account with no
// enabled MFA — callers should check IsMfaEnabled first to distinguish
// "MFA not required" from "wrong code," which this function alone
// cannot tell apart.
func (state *MfaState) VerifyLoginCode(accountIdentifier string, candidateCode string, now time.Time) (bool, error) {
	state.mutexGuardingRecords.Lock()
	record, wasFound := state.recordsByAccountId[accountIdentifier]
	state.mutexGuardingRecords.Unlock()

	if !wasFound || !record.isEnabled {
		return false, nil
	}

	return totp.VerifyCode(record.secretBase32, candidateCode, now, verificationSkewSteps)
}

// DisableMfa turns MFA off for accountIdentifier entirely (removing the
// stored secret, not just flipping a flag — a subsequent BeginEnrollment
// starts fresh). TODO(real build): this skeleton doesn't require
// re-authentication (password or a valid MFA code) to call this —
// disabling a security feature should never be this cheap in a real
// build; see cmd/server/main.go's handler comment for the same caveat.
func (state *MfaState) DisableMfa(accountIdentifier string) {
	state.mutexGuardingRecords.Lock()
	defer state.mutexGuardingRecords.Unlock()
	delete(state.recordsByAccountId, accountIdentifier)
}
